### ISSUE TITLE
Action does not work with versions, only with @main

### ISSUE THREAD

**Issue by SimonEismann** [Teakowa/setup-serverless#121]
When using the plugin as following, it works like a charm:

`- uses: Teakowa/setup-serverless@main`

However, the following then fails:

`- uses: Teakowa/setup-serverless@v1.1`

with the following message:

`Failed to resolve action download info. Error: Unable to resolve action `Teakowa/setup-serverless@v1.1`, unable to find version `v1.1``

I am new to Github actions, so this might also be an issue on my end :)

**Comment by Teakowa** [comment]
I'll check this, thanks for your feedback❤️

**Comment by Teakowa** [comment]
It seems to be a problem with my document writing that, supported versions on the [marketplace](https://github.com/marketplace/actions/setup-serverless-environment) do not include v1 and v1.1.

So I suggest you use the marketplace use latest version to set the action. In your case, just replace `v1.1` to `v1.1.0`, It should work just fine.

And if you want the action follow release version, you can use dependabot([docs](https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates#enabling-dependabot-version-updates)), it will automatically update packages or actions you use.

**Comment by SimonEismann** [comment]
That solved the issue, thanks :)
